# Generated by Django 3.2.5 on 2021-09-11 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_pledge'),
    ]

    operations = [
        migrations.AddField(
            model_name='pledge',
            name='supporter',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
